version: '3.4'

services:
  iak-elastic:
    container_name: iak-elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:6.0.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      CLUSTER_NAME: "istex-api-kibana"
      ES_JAVA_OPTS: ${IAK_ELASTICSEARCH_JAVA_OPTS}
    networks:
      - iak-network      
    volumes:
      - "./data/elastic/data:/usr/share/elasticsearch/data"
      - "./iak-elastic/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
      #- "./iak-elastic/config/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties"
    restart: unless-stopped

  iak-kibana:
    container_name: iak-kibana
    image: docker.elastic.co/kibana/kibana:6.0.0
    ports:
      - 5601:5601
    links:
      - iak-elastic
    environment:
      CLUSTER_NAME: "istex-api-kibana"
      ELASTICSEARCH_URL: "http://iak-elastic:9200"
    networks:
      - iak-network      
    volumes:
      - ./iak-kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    restart: unless-stopped

  iak-rp:
    container_name: iak-rp
    build:
      context: ./iak-rp
      args:
        - http_proxy
        - https_proxy
    image: iak-rp
    environment:
      IAK_BASEURL: ${IAK_BASEURL}
      IAK_ADMIN_USERNAME: ${IAK_ADMIN_USERNAME}
      IAK_ADMIN_PASSWORD: ${IAK_ADMIN_PASSWORD}
    ports:
      - 8080:80
    links:
      - iak-kibana
    networks:
      - iak-network
    volumes:
      - ./logs/iak-rp/:/var/log/nginx/
      - ./iak-rp/entrypoint-create-credentials:/bin/entrypoint-create-credentials
      - ./iak-rp/nginx.debug.conf:/etc/nginx/nginx.conf
    restart: unless-stopped

networks:
  iak-network:
    driver: bridge
