version: '3.4'

services:
  iak-elastic:
    container_name: iak-elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.2
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      CLUSTER_NAME: "istex-kibana"
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - iak-network      
    volumes:
      - "./data/elastic/data:/usr/share/elasticsearch/data"
      - "./iak-elastic/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
      #- "./iak-elastic/config/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties"
    restart: unless-stopped

  iak-kibana:
    container_name: iak-kibana
    image: docker.elastic.co/kibana/kibana:5.4.2
    ports:
      - 5601:5601
    links:
      - iak-elastic
    environment:
      - ELASTICSEARCH_URL="http://iak-elastic:9200"
    networks:
      - iak-network      
    volumes:
      - ./iak-kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    restart: unless-stopped

networks:
  iak-network:
    driver: bridge
