version: '3.4'

services:

  # elasticsearch engine
  iak-elastic:
    container_name: iak-elastic
    build:
      context: ./iak-elastic
      args:
        - http_proxy
        - https_proxy
    image: istex/istex-api-kibana:1.1.0-elastic
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      CLUSTER_NAME: "istex-api-kibana"
      ES_JAVA_OPTS: ${IAK_ELASTICSEARCH_JAVA_OPTS}
      TAKE_FILE_OWNERSHIP: "1" # to be able to write into /usr/share/elasticsearch/data/
    networks:
      - iak-network      
    volumes:
      - ./data/elastic/data/:/usr/share/elasticsearch/data/
      - ./iak-elastic/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    restart: unless-stopped




  # kibana web server
  iak-kibana:
    container_name: iak-kibana
    build:
      context: ./iak-kibana
      args:
        - http_proxy
        - https_proxy
    image: istex/istex-api-kibana:1.1.0-kibana
    ports:
      - 5601:5601
    links:
      - iak-elastic
    environment:
      CLUSTER_NAME: "istex-api-kibana"
      ELASTICSEARCH_URL: "http://iak-elastic:9200"
    networks:
      - iak-network      
    volumes:
      - ./iak-kibana/kibana.debug.yml:/usr/share/kibana/config/kibana.yml
    restart: unless-stopped



  # enduser entrypoint
  # (nginx reverse proxy dedicated to admin authentication stuff)
  iak-rp:
    container_name: iak-rp
    build:
      context: ./iak-rp
      args:
        - http_proxy
        - https_proxy
    image: istex/istex-api-kibana:1.1.0-rp
    environment:
      IAK_BASEURL: ${IAK_BASEURL}
      IAK_ADMIN_USERNAME: ${IAK_ADMIN_USERNAME}
      IAK_ADMIN_PASSWORD: ${IAK_ADMIN_PASSWORD}
    ports:
      - 8080:80
    links:
      - iak-kibana
    networks:
      - iak-network
    volumes:
      - ./logs/iak-rp/:/var/log/nginx/
      - ./iak-rp/entrypoint-create-credentials:/bin/entrypoint-create-credentials
      - ./iak-rp/nginx.debug.conf:/etc/nginx/nginx.conf
    restart: unless-stopped



  # this container will ingest data into
  # iak-elastic comming from the ISTEX API
  iak-loader:
    container_name: iak-loader
    build:
      context: ./iak-loader
      args:
        - http_proxy
        - https_proxy
    image: istex/istex-api-kibana:1.1.0-loader
    environment:
      ELASTICSEARCH_URL: "http://iak-elastic:9200"
      IAK_ISTEX_API_URL: ${IAK_ISTEX_API_URL}
      IAK_LOAD_10_DOC: ${IAK_LOAD_10_DOC} # load 10 doc at startup
    links:
      - iak-elastic
    networks:
      - iak-network
    volumes:
      - ./iak-loader/create-index-mapping.sh:/bin/create-index-mapping.sh
      - ./iak-loader/load-random-istex-doc.sh:/bin/load-random-istex-doc.sh
      - ./iak-loader/load-random-istex-doc-bulk.sh:/bin/load-random-istex-doc-bulk.sh
      - ./iak-loader/docker-entrypoint.sh:/bin/docker-entrypoint.sh
    restart: unless-stopped


networks:
  iak-network:
    driver: bridge
