cluster.name: ${CLUSTER_NAME}
network.host: 0.0.0.0
script.inline: true
xpack.monitoring.enabled: false
xpack.security.enabled: false
discovery.type: single-node
path.logs: /usr/share/elasticsearch/logs

# to remove the [F3YLXD3] rerouting shards: [high disk watermark exceeded on one or more nodes]
# https://www.elastic.co/guide/en/elasticsearch/reference/2.1/disk-allocator.html
cluster.routing.allocation.disk.threshold_enabled: false
